---

- name: "Go-Lang | Download distribution"
  get_url:
    url: "{{ go_custom_mirror }}/{{ go_distribution_filename }}.tar.gz"
    dest: "{{ go_temporary_dir }}/{{ go_distribution_filename }}.tar.gz"
    checksum: "{{ go_checksum | default('') }}"
    validate_certs: no

- name: "Go-Lang | Empty destination directory"
  file:
    path: "{{ GOROOT }}"
    state: absent
  become: yes

- name: "Go-Lang | Ensure directory is writable"
  file:
    path: "{{ GOROOT }}"
    state: directory
    owner: "{{ fubarhouse_user }}"
    mode: 0755
    recurse: true
  become: yes

# Match tar -C /usr/local -xzf go1.15.7.linux-amd64.tar.gz
- name: "Go-Lang | Unpack distribution"
  unarchive:
    src: "{{ go_temporary_dir }}/{{ go_distribution_filename }}.tar.gz"
    dest: "/usr/local"
    copy: "no"
